baseURL = "https://davidweisscode.github.io/"
languageCode = "en-us"
title = "David Weiß"
copyright = "© David Weiß"

[params]
	mode="auto" # color-mode → light,dark or auto
	featherIconsCDN=true
	subtitle = "My subtitle with a [link](https://github.com/davidweisscode)"

# Social Tags

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:davidweisspost@gmail.com"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/davidweisslink/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/davidweisscode"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/davidweissnews/"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/davidweissbook"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/davidweisspics/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Now"
url = "/now"
weight = 4
